export interface RoleDefinition {
  slug: string;
  title: string;
  keywords: string[];
  atsKeywords: string[];
  mistakes: string[];
  structureTips: string[];
  intro: string;
  relatedBlogSlugs: string[];
}

export const ROLE_SLUGS = [
  "software-engineer",
  "data-scientist",
  "product-manager",
  "marketing-manager",
  "sales-representative",
  "business-analyst",
  "project-manager",
  "ux-designer",
  "data-analyst",
  "devops-engineer",
  "frontend-developer",
  "backend-developer",
  "full-stack-developer",
  "machine-learning-engineer",
  "graphic-designer",
  "content-writer",
  "hr-manager",
  "financial-analyst",
  "nurse",
  "teacher",
] as const;

export type RoleSlug = (typeof ROLE_SLUGS)[number];

function role(
  slug: RoleSlug,
  title: string,
  atsKeywords: string[],
  mistakes: string[],
  structureTips: string[],
  intro: string,
  relatedBlogSlugs: string[]
): RoleDefinition {
  return {
    slug,
    title,
    keywords: [
      `resume optimizer for ${title.toLowerCase()}`,
      `${title.toLowerCase()} resume ATS`,
      `ATS ${title.toLowerCase()} resume checker`,
    ],
    atsKeywords,
    mistakes,
    structureTips,
    intro,
    relatedBlogSlugs,
  };
}

export const ROLES: Record<RoleSlug, RoleDefinition> = {
  "software-engineer": role(
    "software-engineer",
    "Software Engineer",
    [
      "Python",
      "Java",
      "JavaScript",
      "TypeScript",
      "AWS",
      "system design",
      "REST APIs",
      "CI/CD",
      "agile",
      "code review",
      "unit testing",
      "microservices",
    ],
    [
      "Listing technologies without context or project outcomes",
      "Using creative resume layouts that break ATS parsers",
      "Omitting scale metrics — users served, latency, uptime",
      "Generic job titles that don't match the posting language",
    ],
    [
      "Lead with a Technical Skills section grouped by language and platform",
      "Use bullets formatted as: action + technology + measurable result",
      "Mirror exact framework names from the job description",
      "Keep one column, standard fonts, and text-based PDF export",
    ],
    `Software engineering roles attract hundreds of applicants per posting, and ATS systems filter resumes before any engineer reviews your GitHub. Our resume optimizer for software engineers analyzes job descriptions for frameworks like React, Node.js, Python, AWS, and system design keywords — then tailors bullet points to match without inventing experience.`,
    ["software-engineer-resume-ats", "how-to-beat-ats-systems-2025", "resume-keywords-complete-guide"]
  ),
  "data-scientist": role(
    "data-scientist",
    "Data Scientist",
    [
      "Python",
      "R",
      "SQL",
      "machine learning",
      "TensorFlow",
      "PyTorch",
      "A/B testing",
      "statistical modeling",
      "feature engineering",
      "data visualization",
      "pandas",
      "scikit-learn",
    ],
    [
      "Burying ML projects without business impact metrics",
      "Listing algorithms without naming datasets or model performance",
      "Ignoring stakeholder communication keywords in postings",
      "Using academic CV format instead of industry resume structure",
    ],
    [
      "Balance technical skills with business outcomes in every bullet",
      "Include experiment design, model metrics, and deployment context",
      "Add a Projects section with links when ATS allows plain URLs",
      "Tailor summary to domain: fintech, healthcare, e-commerce, etc.",
    ],
    `Data science resumes must balance technical depth with business impact. ATS platforms scan for Python, SQL, TensorFlow, experimentation, and stakeholder communication. Our resume optimizer maps your experience against each job description's exact terminology.`,
    ["resume-keywords-complete-guide", "software-engineer-resume-ats"]
  ),
  "product-manager": role(
    "product-manager",
    "Product Manager",
    [
      "product roadmap",
      "user research",
      "A/B testing",
      "Jira",
      "SQL",
      "stakeholder management",
      "go-to-market",
      "OKRs",
      "Agile",
      "product analytics",
      "Amplitude",
      "cross-functional",
    ],
    [
      "Feature lists without revenue, retention, or growth metrics",
      "Missing tool names recruiters filter on: Jira, Figma, Amplitude",
      "Vague ownership — not clarifying scope and team size",
      "Creative templates that hide keywords in graphics",
    ],
    [
      "Quantify outcomes: DAU, conversion, NPS, revenue impact",
      "Use PM-specific verbs: prioritized, shipped, validated, aligned",
      "Mirror job title variants: PM, product owner, technical PM",
      "Keep experience bullets under two lines for parser clarity",
    ],
    `Product manager resumes compete on outcomes: roadmap delivery, user growth, and data-driven decisions. ATS systems keyword-match titles and tools like Jira and SQL. Tailor each application with our free resume optimizer.`,
    ["how-to-beat-ats-systems-2025", "why-resume-rejected-ats"]
  ),
  "marketing-manager": role(
    "marketing-manager",
    "Marketing Manager",
    [
      "SEO",
      "SEM",
      "Google Analytics",
      "content strategy",
      "email marketing",
      "HubSpot",
      "conversion rate",
      "brand awareness",
      "paid social",
      "marketing automation",
      "ROI",
      "campaign management",
    ],
    [
      "Campaign descriptions without ROI or pipeline contribution",
      "Missing channel-specific keywords from the posting",
      "Design-heavy resumes that ATS cannot parse",
      "Generic 'managed marketing' bullets without platform names",
    ],
    [
      "Lead bullets with metrics: CTR, CAC, MQLs, revenue attributed",
      "Name every platform and tool mentioned in the job description",
      "Separate skills by channel: paid, organic, email, content",
      "Use standard section headings recruiters expect",
    ],
    `Marketing resumes must speak each channel's language. ATS filters look for SEO, paid media, CRM platforms, and conversion metrics. Tailor your resume to each posting with our ATS resume checker.`,
    ["resume-keywords-complete-guide", "ats-friendly-resume-format"]
  ),
  "sales-representative": role(
    "sales-representative",
    "Sales Representative",
    [
      "quota attainment",
      "pipeline generation",
      "Salesforce",
      "CRM",
      "B2B sales",
      "prospecting",
      "negotiation",
      "account management",
      "cold outreach",
      "SaaS sales",
      "closing",
      "territory management",
    ],
    [
      "No quota numbers or percentage attainment",
      "Omitting CRM and sales stack keywords",
      "Soft bullets like 'exceeded expectations' without figures",
      "Multi-column sales resume templates",
    ],
    [
      "Put quota attainment in the first bullet of each role",
      "Include deal size, cycle length, and vertical/industry",
      "Match title language: SDR, BDR, AE, account executive",
      "Use simple single-column DOCX for ATS submissions",
    ],
    `Sales roles demand quota attainment and CRM fluency on every resume. ATS systems search for Salesforce, outbound prospecting, and revenue numbers. Tailor each posting with our free optimizer.`,
    ["why-resume-rejected-ats", "how-to-beat-ats-systems-2025"]
  ),
  "business-analyst": role(
    "business-analyst",
    "Business Analyst",
    [
      "requirements gathering",
      "SQL",
      "Jira",
      "Confluence",
      "process improvement",
      "stakeholder management",
      "UML",
      "Agile",
      "data analysis",
      "user stories",
      "BRD",
      "gap analysis",
    ],
    [
      "Process descriptions without efficiency or cost savings metrics",
      "Missing methodology keywords: Agile, Scrum, Waterfall",
      "Tables used for layout that break ATS parsing",
      "Not mirroring industry domain from the job posting",
    ],
    [
      "Quantify process improvements: time saved, error reduction",
      "List tools explicitly: SQL, Excel, Power BI, Jira",
      "Use BA action verbs: elicited, documented, validated, facilitated",
      "Tailor summary to industry: finance, healthcare, tech",
    ],
    `Business analyst ATS filters scan for requirements documentation, SQL, Agile, and stakeholder management. Our optimizer aligns your resume with each role's domain and tooling keywords.`,
    ["resume-keywords-complete-guide", "ats-friendly-resume-format"]
  ),
  "project-manager": role(
    "project-manager",
    "Project Manager",
    [
      "PMP",
      "Agile",
      "Scrum",
      "risk management",
      "budget management",
      "stakeholder communication",
      "MS Project",
      "Jira",
      "cross-functional teams",
      "project lifecycle",
      "resource allocation",
      "delivery",
    ],
    [
      "Project lists without budget, timeline, or team size",
      "Missing certification keywords when applicable",
      "Combining unrelated projects without role context",
      "Non-standard headings like 'Projects I Led'",
    ],
    [
      "Format bullets as: scope + budget/timeline + outcome",
      "Include methodology: Agile, Waterfall, hybrid",
      "Name industries and project types matching the posting",
      "Place PMP or Scrum Master certs in a dedicated section",
    ],
    `Project manager resumes must show delivery at scale. ATS systems filter on PMP, Agile, budget ownership, and risk management. Tailor each application with keyword-aligned bullets.`,
    ["how-to-beat-ats-systems-2025", "why-resume-rejected-ats"]
  ),
  "ux-designer": role(
    "ux-designer",
    "UX Designer",
    [
      "user research",
      "wireframing",
      "prototyping",
      "Figma",
      "Sketch",
      "usability testing",
      "design systems",
      "information architecture",
      "accessibility",
      "WCAG",
      "user flows",
      "interaction design",
    ],
    [
      "Portfolio-only submissions without text-based resume",
      "Embedding critical text inside portfolio images",
      "Missing research and testing methodology keywords",
      "Omitting accessibility and design system experience",
    ],
    [
      "Describe research methods and sample sizes in text bullets",
      "Name tools exactly as listed in the job description",
      "Include metrics: task success rate, NPS, conversion lift",
      "Submit a parser-friendly DOCX alongside portfolio link",
    ],
    `UX design resumes must be ATS-readable, not just visually impressive. Parsers need text descriptions of research, prototyping tools, and measurable design impact. Our optimizer tailors keywords per posting.`,
    ["ats-friendly-resume-format", "resume-keywords-complete-guide"]
  ),
  "data-analyst": role(
    "data-analyst",
    "Data Analyst",
    [
      "SQL",
      "Excel",
      "Python",
      "Tableau",
      "Power BI",
      "data visualization",
      "reporting",
      "dashboards",
      "ETL",
      "statistical analysis",
      "business intelligence",
      "KPI tracking",
    ],
    [
      "Tool lists without analysis outcomes",
      "Missing dashboard and reporting impact metrics",
      "Vague 'analyzed data' bullets",
      "Complex chart graphics instead of text descriptions",
    ],
    [
      "Lead with business questions answered and decisions enabled",
      "Name BI tools matching the posting exactly",
      "Include SQL complexity context when relevant",
      "Keep layout single-column for ATS compatibility",
    ],
    `Data analyst roles require SQL, visualization tools, and clear reporting impact. ATS filters match Tableau, Power BI, and Python keywords. Optimize your resume for each job description free.`,
    ["resume-keywords-complete-guide", "software-engineer-resume-ats"]
  ),
  "devops-engineer": role(
    "devops-engineer",
    "DevOps Engineer",
    [
      "Kubernetes",
      "Docker",
      "AWS",
      "Terraform",
      "CI/CD",
      "Jenkins",
      "GitHub Actions",
      "Linux",
      "monitoring",
      "infrastructure as code",
      "Ansible",
      "SRE",
    ],
    [
      "Infrastructure lists without reliability or deployment metrics",
      "Missing IaC and cloud provider keywords",
      "Omitting incident response and uptime outcomes",
      "Abbreviations without spelling out tools first",
    ],
    [
      "Quantify: deployment frequency, MTTR, uptime, cost reduction",
      "Group skills: cloud, CI/CD, monitoring, security",
      "Mirror exact stack from job description",
      "Use standard Experience section with employer names parseable",
    ],
    `DevOps resumes must surface Kubernetes, cloud platforms, and CI/CD pipelines in ATS-scannable text. Our optimizer matches infrastructure keywords to each posting.`,
    ["software-engineer-resume-ats", "resume-keywords-complete-guide"]
  ),
  "frontend-developer": role(
    "frontend-developer",
    "Frontend Developer",
    [
      "React",
      "TypeScript",
      "JavaScript",
      "HTML",
      "CSS",
      "Next.js",
      "responsive design",
      "accessibility",
      "Redux",
      "Webpack",
      "performance optimization",
      "UI components",
    ],
    [
      "Framework buzzwords without project context",
      "Missing accessibility and performance keywords",
      "Portfolio links buried where parsers skip them",
      "Multi-column skill grids",
    ],
    [
      "Tie each framework to shipped features and user impact",
      "Include Core Web Vitals or performance improvements when true",
      "List accessibility standards: WCAG, ARIA",
      "Export text-based PDF from a simple template",
    ],
    `Frontend developer ATS filters search for React, TypeScript, and modern build tools. Tailor your resume to each posting's exact stack with our free resume keyword optimizer.`,
    ["software-engineer-resume-ats", "ats-friendly-resume-format"]
  ),
  "backend-developer": role(
    "backend-developer",
    "Backend Developer",
    [
      "Node.js",
      "Python",
      "Java",
      "REST APIs",
      "GraphQL",
      "PostgreSQL",
      "MongoDB",
      "microservices",
      "Redis",
      "Kafka",
      "authentication",
      "API design",
    ],
    [
      "API work described without scale or latency metrics",
      "Missing database and messaging system keywords",
      "Omitting security and auth experience when required",
      "Generic 'built APIs' without technology names",
    ],
    [
      "Quantify throughput, latency, and data volume handled",
      "Name databases and queues exactly as in the posting",
      "Separate languages, frameworks, and infrastructure",
      "Use bullets parsers can map to Experience entries",
    ],
    `Backend developer resumes must highlight APIs, databases, and scale. ATS systems match Node, Python, SQL, and cloud keywords. Optimize per job description with our ATS checker.`,
    ["software-engineer-resume-ats", "resume-keywords-complete-guide"]
  ),
  "full-stack-developer": role(
    "full-stack-developer",
    "Full Stack Developer",
    [
      "React",
      "Node.js",
      "TypeScript",
      "PostgreSQL",
      "REST APIs",
      "AWS",
      "Docker",
      "MongoDB",
      "full stack",
      "JavaScript",
      "CI/CD",
      "agile",
    ],
    [
      "Listing full stack without depth on either frontend or backend",
      "Missing end-to-end ownership metrics",
      "Too many technologies without project association",
      "Unparseable skill tag clouds",
    ],
    [
      "Show end-to-end delivery: design through deployment",
      "Balance frontend and backend keywords from the posting",
      "Include one strong full-stack project bullet per role",
      "Keep skills section categorized, not a word cloud image",
    ],
    `Full stack roles require both client and server keywords in ATS-scannable format. Our resume optimizer tailors your stack to each MERN, MEAN, or custom posting.`,
    ["software-engineer-resume-ats", "how-to-beat-ats-systems-2025"]
  ),
  "machine-learning-engineer": role(
    "machine-learning-engineer",
    "Machine Learning Engineer",
    [
      "PyTorch",
      "TensorFlow",
      "Python",
      "MLOps",
      "model deployment",
      "feature engineering",
      "deep learning",
      "NLP",
      "computer vision",
      "Kubernetes",
      "AWS SageMaker",
      "experiment tracking",
    ],
    [
      "Research papers listed without production deployment context",
      "Missing MLOps and pipeline keywords",
      "Model accuracy without dataset or business context",
      "Academic formatting incompatible with ATS",
    ],
    [
      "Emphasize production ML: serving, monitoring, retraining",
      "Include model metrics and business KPIs together",
      "Name ML platforms and experiment tools from the posting",
      "Use industry resume format, not CV, unless required",
    ],
    `ML engineer ATS filters weigh production deployment, MLOps, and framework keywords heavily. Tailor your resume to each posting with our AI resume optimizer.`,
    ["software-engineer-resume-ats", "resume-keywords-complete-guide"]
  ),
  "graphic-designer": role(
    "graphic-designer",
    "Graphic Designer",
    [
      "Adobe Creative Suite",
      "Photoshop",
      "Illustrator",
      "InDesign",
      "branding",
      "typography",
      "layout design",
      "print design",
      "digital design",
      "Figma",
      "visual identity",
      "campaign creative",
    ],
    [
      "Image-heavy resumes with no extractable text",
      "Portfolio-only applications skipping ATS text fields",
      "Missing Adobe tool names recruiters search for",
      "No metrics on campaign or brand outcomes",
    ],
    [
      "Describe deliverables in text: brand systems, campaigns, formats",
      "Name Adobe tools and versions where relevant",
      "Include client types or industries matching the posting",
      "Submit a plain-text-friendly DOCX plus portfolio URL",
    ],
    `Graphic design resumes often fail ATS because text lives inside images. Our optimizer helps you keep a parser-friendly resume while linking to visual work.`,
    ["ats-friendly-resume-format", "why-resume-rejected-ats"]
  ),
  "content-writer": role(
    "content-writer",
    "Content Writer",
    [
      "SEO writing",
      "content strategy",
      "copywriting",
      "blog writing",
      "CMS",
      "WordPress",
      "editorial calendar",
      "brand voice",
      "Google Analytics",
      "content marketing",
      "editing",
      "AP style",
    ],
    [
      "Writing samples linked without keyword-rich experience bullets",
      "Missing SEO and content strategy terms",
      "No traffic, engagement, or conversion metrics",
      "Creative layouts that break parsers",
    ],
    [
      "Quantify content impact: traffic, rankings, conversions",
      "Name CMS and SEO tools from the job description",
      "Include content types: blog, whitepaper, email, social",
      "Use simple structure with a Writing Experience section",
    ],
    `Content writer ATS filters search for SEO, CMS platforms, and content strategy keywords. Tailor your resume to each editorial or marketing writing role.`,
    ["resume-keywords-complete-guide", "ats-friendly-resume-format"]
  ),
  "hr-manager": role(
    "hr-manager",
    "HR Manager",
    [
      "employee relations",
      "talent acquisition",
      "HRIS",
      "Workday",
      "performance management",
      "compliance",
      "onboarding",
      "benefits administration",
      "DEI",
      "labor law",
      "conflict resolution",
      "organizational development",
    ],
    [
      "HR duties listed without employee population or program scale",
      "Missing HRIS and compliance keywords",
      "Omitting DEI and culture initiatives when in posting",
      "Non-standard HR resume templates",
    ],
    [
      "Quantify: headcount supported, retention, time-to-hire",
      "Name HRIS systems exactly as employers list them",
      "Include certifications: SHRM-CP, PHR when applicable",
      "Use conventional section headings for ATS mapping",
    ],
    `HR manager resumes must surface HRIS, compliance, and people program keywords. Our ATS checker tailors your experience to each organization's requirements.`,
    ["how-to-beat-ats-systems-2025", "ats-friendly-resume-format"]
  ),
  "financial-analyst": role(
    "financial-analyst",
    "Financial Analyst",
    [
      "financial modeling",
      "Excel",
      "VBA",
      "forecasting",
      "variance analysis",
      "FP&A",
      "SQL",
      "Power BI",
      "GAAP",
      "budgeting",
      "DCF",
      "financial reporting",
    ],
    [
      "Models described without business decisions they enabled",
      "Missing Excel and FP&A keywords",
      "Omitting GAAP or industry-specific standards",
      "Dense tables that scramble in ATS parsers",
    ],
    [
      "Lead with models built and decisions supported",
      "Name tools: Excel, SQL, Bloomberg, Capital IQ as applicable",
      "Include accuracy or efficiency improvements with numbers",
      "Use simple rows for experience, not nested tables",
    ],
    `Financial analyst ATS filters scan for modeling, Excel, FP&A, and reporting keywords. Optimize your resume for each finance posting with our free tool.`,
    ["resume-keywords-complete-guide", "why-resume-rejected-ats"]
  ),
  nurse: role(
    "nurse",
    "Nurse",
    [
      "RN",
      "patient care",
      "BLS",
      "ACLS",
      "Epic",
      "Cerner",
      "medication administration",
      "clinical assessment",
      "care plans",
      "EMR",
      "ICU",
      "patient outcomes",
    ],
    [
      "Clinical skills without unit type or patient population",
      "Missing license and certification keywords",
      "Omitting EMR system names",
      "Creative nursing resume templates with icons",
    ],
    [
      "State license and certifications in a dedicated parseable section",
      "Name EMR systems and units matching the posting",
      "Quantify patient ratios and outcomes where appropriate",
      "Use standard Experience format with facility names",
    ],
    `Healthcare employers use ATS to filter nursing resumes by license, specialties, EMR systems, and certifications. Tailor your clinical experience to each unit's requirements.`,
    ["ats-friendly-resume-format", "why-resume-rejected-ats"]
  ),
  teacher: role(
    "teacher",
    "Teacher",
    [
      "lesson planning",
      "classroom management",
      "curriculum development",
      "differentiated instruction",
      "state certification",
      "student assessment",
      "IEP",
      "parent communication",
      "Google Classroom",
      "STEM",
      "literacy",
      "standardized testing",
    ],
    [
      "Creative classroom-themed layouts that break ATS",
      "Certifications buried in prose paragraphs",
      "Missing grade level and subject keywords",
      "No student outcome or assessment data",
    ],
    [
      "Lead with certification, grade level, and subject area",
      "Include assessment and growth metrics when available",
      "Name curriculum standards relevant to the district",
      "Use a simple single-column template for online applications",
    ],
    `School districts use ATS to screen for certification, grade levels, and curriculum keywords. Our optimizer tailors your teaching resume to each district posting.`,
    ["ats-friendly-resume-format", "how-to-beat-ats-systems-2025"]
  ),
};

export function getRole(slug: string): RoleDefinition | null {
  if (slug in ROLES) return ROLES[slug as RoleSlug];
  return null;
}
